### ISSUE TITLE
Exception - Cannot use object of type stdClass

### ISSUE THREAD

**Issue by oscarrc** [alokr912/moodle-mod_gotomeeting#11]
The following exception is thrown when trying to add the module to a course:
![image](https://user-images.githubusercontent.com/7826103/133591845-843abf32-bd35-4856-ab43-d0a3c5350411.png)

**Comment by oscarrc** [comment]
I think you shoud `json_decode($response, true)` in order to it to be treated as an array
Relevant line: https://github.com/alokr912/moodle-mod_gotomeeting/blob/44ac4a850d17813220dde0343eca7f0bb85180f5/lib.php#L31

**Comment by alokr912** [comment]
I am fixing it.

**Comment by alokr912** [comment]
Fixed
