### ISSUE TITLE
Oauth API v2

### ISSUE THREAD

**Issue by robertscally** [alokr912/moodle-mod_gotomeeting#4]
Hi,

I get the following error when trying to use this plugin, you will need to upgrade the plugin
so that it uses Oauth API v2.

OSDResponse Object
(
    [body] => {"error":"OAuth API v1 has been decommissioned as announced in February 2018, please switch to OAuth API v2 documented here: https://goto-developer.logmeininc.com/oauth-migration-guide. Please reach out to Support (developer-support@logmein.com) with questions."}
    [status] => 400
    [headers] => Array
        (
            [server] => nginx
            [date] => Tue, 27 Aug 2019 13:47:08 GMT
            [content-type] => application/json
            [content-length] => 263
            [connection] => keep-alive
            [access-control-allow-headers] => origin, x-requested-with, accept, authorization, content-type
            [access-control-allow-methods] => GET, PUT, POST, DELETE
            [access-control-allow-origin] => *
            [access-control-max-age] => 3628800
        )
)

**Comment by abhishekumarai1** [comment]
I have made changes for auth2.
