### ISSUE TITLE
Missing "save and display" button in course creation

### ISSUE THREAD

**Issue by francesca-chimbo** [alokr912/moodle-mod_gotomeeting#6]
Hello,
I uploaded and set up the gotomeeting plugin, everything seems to be fine but when I try to create a course with gotomeeting I don't have the option to save.
Can you help?
Thank you,
Francesca

**Comment by alokr912** [comment]
Francesca,

Kindly follow the installation instruction , and use verify button on settings page to check your configration.

**Comment by francesca-chimbo** [comment]
Hi Alok,
the installation has been successful, s well as the configuration, here attached the screenshots.
The problem is creating a new course with GoToMeeting: the button “save and display” is missing.







FRANCESCA NIGRO
Professionista in web e social marketing, 
content editing, web design & seo.

francesca@chimbo.it <mailto:francesca@chimbo.it>
+39 329 5484398
 <https://www.chimbo.it/>
The information in this e-mail (which includes any files transmitted with it) is confidential and may also be legally privileged. It is intended for the addressee only. Access to this e-mail by anyone else is unauthorised. It is not to be relied upon by any person other than the addressee, except with our prior written approval. If no such approval is given, we will not accept any liability (in negligence or otherwise) arising from any third party acting, or refraining from acting on such information. Unauthorised recipients are required to maintain confidentiality. If you have received this e-mail in error please notify us immediately, destroy any copies and delete it from your computer system. Any use, dissemination, forwarding, printing or copying of this e-mail is prohibited. Copyright in this e-mail and any document created by us will be and remain vested in us and will not be transferred to you. We assert the right to be identified as the author of and to object to any misuses of the contents of this e-mail info@chimbo.it <mailto:info@chimbo.it> or such documents.

**Comment by alokr912** [comment]
Kindly share me the configuration test screenshot.

**Comment by francesca-chimbo** [comment]
Here it is:




FRANCESCA NIGRO
Professionista in web e social marketing, 
content editing, web design & seo.

francesca@chimbo.it <mailto:francesca@chimbo.it>
+39 329 5484398
 <https://www.chimbo.it/>
The information in this e-mail (which includes any files transmitted with it) is confidential and may also be legally privileged. It is intended for the addressee only. Access to this e-mail by anyone else is unauthorised. It is not to be relied upon by any person other than the addressee, except with our prior written approval. If no such approval is given, we will not accept any liability (in negligence or otherwise) arising from any third party acting, or refraining from acting on such information. Unauthorised recipients are required to maintain confidentiality. If you have received this e-mail in error please notify us immediately, destroy any copies and delete it from your computer system. Any use, dissemination, forwarding, printing or copying of this e-mail is prohibited. Copyright in this e-mail and any document created by us will be and remain vested in us and will not be transferred to you. We assert the right to be identified as the author of and to object to any misuses of the contents of this e-mail info@chimbo.it <mailto:info@chimbo.it> or such documents.

**Comment by alokr912** [comment]
None of your screenshot is visible.

**Comment by francesca-chimbo** [comment]
Let me know if you can open them now



FRANCESCA NIGRO
Professionista in web e social marketing, 
content editing, web design & seo.

francesca@chimbo.it <mailto:francesca@chimbo.it>
+39 329 5484398
 <https://www.chimbo.it/>
The information in this e-mail (which includes any files transmitted with it) is confidential and may also be legally privileged. It is intended for the addressee only. Access to this e-mail by anyone else is unauthorised. It is not to be relied upon by any person other than the addressee, except with our prior written approval. If no such approval is given, we will not accept any liability (in negligence or otherwise) arising from any third party acting, or refraining from acting on such information. Unauthorised recipients are required to maintain confidentiality. If you have received this e-mail in error please notify us immediately, destroy any copies and delete it from your computer system. Any use, dissemination, forwarding, printing or copying of this e-mail is prohibited. Copyright in this e-mail and any document created by us will be and remain vested in us and will not be transferred to you. We assert the right to be identified as the author of and to object to any misuses of the contents of this e-mail info@chimbo.it <mailto:info@chimbo.it> or such documents.

**Comment by alokr912** [comment]
send me directly on alokr.mail@gmail.com

**Comment by francesca-chimbo** [comment]
Hi Alok,
did you receive the email I sent to alokr.mail@gmail.com <mailto:alokr.mail@gmail.com>?
F.


FRANCESCA NIGRO
Professionista in web e social marketing, 
content editing, web design & seo.

francesca@chimbo.it <mailto:francesca@chimbo.it>
+39 329 5484398
 <https://www.chimbo.it/>
The information in this e-mail (which includes any files transmitted with it) is confidential and may also be legally privileged. It is intended for the addressee only. Access to this e-mail by anyone else is unauthorised. It is not to be relied upon by any person other than the addressee, except with our prior written approval. If no such approval is given, we will not accept any liability (in negligence or otherwise) arising from any third party acting, or refraining from acting on such information. Unauthorised recipients are required to maintain confidentiality. If you have received this e-mail in error please notify us immediately, destroy any copies and delete it from your computer system. Any use, dissemination, forwarding, printing or copying of this e-mail is prohibited. Copyright in this e-mail and any document created by us will be and remain vested in us and will not be transferred to you. We assert the right to be identified as the author of and to object to any misuses of the contents of this e-mail info@chimbo.it <mailto:info@chimbo.it> or such documents.

**Comment by ruferher** [comment]
Do you have the solution? I hace the same problem
