### ISSUE TITLE
GoToMeeting integrations in Moodle

### ISSUE THREAD

**Issue by bhodeler** [alokr912/moodle-mod_gotomeeting#9]
![Captura1](https://user-images.githubusercontent.com/16878146/94457525-f6b91d80-01b4-11eb-884c-f2161983f1a5.JPG)
Hello,

I´ve recently purchased a license from GoToMeeting and would need to know how to obtain GoToMeeting Consumer key. Please, could you give me instructions to do that?

Regards.

Mario.

**Comment by olemde** [comment]
Hello Mario.
sorry i could not answer your problem but i have the same issue. Have you found already a solution?
br
Ole

**Comment by alokr912** [comment]
I will be planning to upgrade this latest API  by 31-Oct.

It would be helpful if anyone shares the license for testing.

**Comment by bhodeler** [comment]
Hello,

Thanks for your support.

I can share license; please, tell me what info do you need exactly?

Regards.

Mario.

De: Alok Kumar <notifications@github.com>
Enviado el: lunes, 12 de octubre de 2020 13:00
Para: alokr912/moodle-mod_gotomeeting <moodle-mod_gotomeeting@noreply.github.com>
CC: bhodeler <mario@impulsotecnologico.com>; Author <author@noreply.github.com>
Asunto: Re: [alokr912/moodle-mod_gotomeeting] GoToMeeting integrations in Moodle (#9)


I will be planning to upgrade this latest API by 31-Oct.

It would be helpful if anyone shares the license for testing.

**Comment by alokr912** [comment]
<img width="960" alt="go" src="https://user-images.githubusercontent.com/5538664/95771612-feaaae80-0cd8-11eb-90ae-55233d91a497.png">

Do Share user id and password on my email alokr.mail@gmail.com
